## Numpy Arrays

In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.1'

## Criando Arrays

In [5]:
#Array unidimensional ou vetor
vetor1 = np.array([1,2,3,4,5,6,7,8,9])

In [6]:
print(vetor1)

[1 2 3 4 5 6 7 8 9]


## Criando Matrizes

In [7]:
matrix = np.array([[1,2,3],[4,5,6]])

In [8]:
print(matrix)

[[1 2 3]
 [4 5 6]]


In [9]:
matrix.shape

(2, 3)

In [11]:
matrix1 = np.ones((5,5))

In [12]:
matrix1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
lista = [[2,4,6],[8,10,12],[1,1,1]]

In [16]:
matrix2 = np.matrix(lista)

In [17]:
matrix2

matrix([[ 2,  4,  6],
        [ 8, 10, 12],
        [ 1,  1,  1]])

In [18]:
matrix2.size

9

In [21]:
x = np.array([1,2,3], dtype = np.int64)
print(x.dtype)
print(x)

int64
[1 2 3]
